[server]
port = 50003
postgres_url = "postgresql://postgres:sx931210@0.0.0.0:5432/postgres"
postgres_url_read = "postgresql://postgres:sx931210@0.0.0.0:5432/postgres"
redis_url = "redis://0.0.0.0:6379"
request_id_header = "X-Request-ID"

[jwt]
period_seconds = 604800
sk = """
-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIDnxJGEJGoW+mNKHn4vRY1V6BQ3MglSQSuZ8featmyC4
-----END PRIVATE KEY-----
"""
pk = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAfM+lwNHj6TRJ3EGP38lIJcOo9Dlt2u2JzcwWMbu7jQY=
-----END PUBLIC KEY-----
"""

[kafka]
brokers = ["alikafka-post-cn-ux145v8ke00d-1-vpc.alikafka.aliyuncs.com:9092", "alikafka-post-cn-ux145v8ke00d-2-vpc.alikafka.aliyuncs.com:9092", "alikafka-post-cn-ux145v8ke00d-3-vpc.alikafka.aliyuncs.com:9092"]
